content/home.json
template/pages/@/layout/footer.ejs
template/pages/@/views/components/banner-slider.ejs

Alt tag e link aria-label on footer

feat: changes for lighthouse

---

CODE_OF_CONDUCT.md

chore(code-of-conduct): default Contributor Covenant Code of Conduct

---

@ecomplus/storefront-template/template/js/netlify-cms/base-config/collections/extra-pages.js

**Summary**
There is a "code" field that has no use in this page. This commit removes it
lol

fix(cms): removing code in extrapage config

---

@ecomplus/storefront-template/template/js/netlify-cms/base-config/collections/layout/header.js
@ecomplus/storefront-template/template/pages/@/layout/header.ejs

Suggestion from community. To set a background color and color from text inside tarja marketing

feat(cms-header): set background or color of tarja marketing only

---

@ecomplus/widget-compre-confie/src/index.js

fix: change invalid params

---

@ecomplus/storefront-app/src/components/html/CreditCardForm.html
@ecomplus/storefront-app/src/components/js/CreditCardForm.js
@ecomplus/storefront-app/src/components/scss/CreditCardForm.scss

https://github.com/ecomplus/storefront/issues/561#event-5600668818
**Summary**
Implementing of a loading spinner for when CreditCardHash is created
**Checklist**

Implementing of a loading spinner for when CreditCardHash is created

---

@ecomplus/storefront-components/src/html/ProductVariations.html
@ecomplus/storefront-components/src/html/TheProduct.html
@ecomplus/storefront-components/src/js/ProductVariations.js
@ecomplus/storefront-components/src/js/TheProduct.js
@ecomplus/storefront-components/src/scss/ProductVariations.scss
@ecomplus/storefront-components/src/scss/TheProduct.scss
@ecomplus/widget-offers-notification/src/append/product-slots.ejs

https://github.com/ecomplus/storefront/issues/562
**Summary**
Pops out item notification when a certain variation is up to buy
**Checklist**

feat(product-variations): add "tell me when available" support

---

@ecomplus/storefront-components/src/js/LoginBlock.js
@ecomplus/storefront-components/src/js/LoginModal.js

Era possível criar conta com mesmo email, mas com alguma letra maiscula, mas é o mesmo email

fix(login): check email with lowercase

---

@ecomplus/widget-fb-pixel/src/lib/watch-app-routes.js

fix(widget-fb-pixel): get amount for value from order router param

---

@ecomplus/storefront-twbs/scss/_functions.scss
@ecomplus/storefront-twbs/scss/_mixins.scss
@ecomplus/storefront-twbs/scss/_variables.scss
@ecomplus/storefront-twbs/scss/_vars.scss
@ecomplus/storefront-twbs/scss/components/_pagination.scss
@ecomplus/storefront-twbs/scss/mixins/_background-variant.scss
@ecomplus/storefront-twbs/scss/mixins/_float.scss
@ecomplus/storefront-twbs/scss/mixins/_grid-framework.scss
@ecomplus/storefront-twbs/scss/mixins/_hover.scss
@ecomplus/storefront-twbs/scss/mixins/_nav-divider.scss
@ecomplus/storefront-twbs/scss/mixins/_screen-reader.scss
@ecomplus/storefront-twbs/scss/mixins/_size.scss
@ecomplus/storefront-twbs/scss/mixins/_text-emphasis.scss
@ecomplus/storefront-twbs/scss/mixins/_text-hide.scss
@ecomplus/storefront-twbs/scss/mixins/_visibility.scss
@ecomplus/storefront-twbs/scss/presets/_colors.scss
@ecomplus/storefront-twbs/scss/styles.scss
@ecomplus/storefront-twbs/scss/utilities/_clearfix.scss
@ecomplus/storefront-twbs/scss/utilities/_display.scss
@ecomplus/storefront-twbs/scss/utilities/_embed.scss
@ecomplus/storefront-twbs/scss/utilities/_position.scss
@ecomplus/storefront-twbs/scss/utilities/_screenreaders.scss

https://github.com/ecomplus/storefront/issues/509
**Summary**
Fixes for minimal startup with BS5 Saas:
- Tests with `npx lerna run --scope=@ecomplus/storefront-twbs serve` working (demo JS not working yet);
- `npx lerna run --scope=@ecomplus/storefront-twbs build` outputs:
```console
7e0303f9bd7cac3d7a83765845b5364b.woff2  12.5 KiB          [emitted] [immutable]  
add975d8a182422cc76087b01611f56f.woff  14.9 KiB          [emitted] [immutable]  
storefront-twbs.bundle.min.js  82.8 KiB       0  [emitted]              main
storefront-twbs.bundle.min.js.map   355 KiB       0  [emitted] [dev]        main
storefront-twbs.min.css   107 KiB       0  [emitted]              main
storefront-twbs.min.css.map   136 KiB       0  [emitted] [dev]        main
``` …

Refactor/ BS5 startup

---

@ecomplus/storefront-template/template/pages/@/layout/header.ejs

With identification at desktop categories, our agencies can style each category link for desktop

chore(header.ejs) : add id on desktop categories

---

@ecomplus/storefront-template/template/scss/themes/ecom-beauty/_custom.scss

https://github.com/ecomplus/storefront/issues/706
**Summary**
Apply some adjustments to Ecom.Beauy theme according suggestions of the RFC
**Checklist**

fix(themes/ecom-beauty): ECom.Beauty styles fine tune

---

@ecomplus/storefront-template/template/js/netlify-cms/base-config/collections/settings/info.js
@ecomplus/storefront-template/template/pages/@/sections/info-bar.ejs

**Summary**
Add title on info-bar item in order to apply different styles to them
**Checklist**

feat(sections/info-bar): add title on info bar items

---

@ecomplus/storefront-template/template/js/lib/fallback-404.js
@ecomplus/storefront-template/template/js/lib/get-scoped-slots.js
@ecomplus/storefront-template/template/js/lib/menu.js
@ecomplus/storefront-template/template/js/lib/search.js
@ecomplus/storefront-template/template/js/lib/utils.js

**Summary**
jQuery removal from storefront-template files
**Checklist**

fix(storefront-template): remove jQuery from storefront-template files

---

@ecomplus/widget-search-engine/src/index.js

**Summary**
Remove jQuery from widget search engine
**Checklist**

fix(widget-search-engine): remove jQuery from widget search engine

---

@ecomplus/storefront-app/src/plugins/toast.js

**Summary**
Remove jQuery from storefront-app plugins
**Checklist**

fix(plugins/toast): remove jQuery from plugins

---

@ecomplus/storefront-app/src/components/js/CreditCardForm.js

**Summary**
Remove jQuery from storefront-app components
**Checklist**

fix(components): remove jQuery from components

---

@ecomplus/storefront-template/template/pages/@/layout/header.ejs

Just add tiktok on header just like already has on footer

chore(template/header): add tiktok on header

---

@ecomplus/storefront-template/template/js/netlify-cms/base-config/sections.js

chore (sections) : add default empty datetime on create slider banner

---

@ecomplus/storefront-components/src/html/TheProduct.html
@ecomplus/storefront-components/src/js/QuantitySelector.js
@ecomplus/storefront-components/src/js/TheProduct.js

https://github.com/ecomplus/storefront/issues/780

Show correctly quantity on input component and use quantity from input in to shipping calculator

---

@ecomplus/widget-fb-pixel/src/lib/watch-app-routes.js

fix(pixel/purchase) : only emit purchase if is orderJson

---

@ecomplus/storefront-template/template/scss/components/_header.scss

https://github.com/ecomplus/storefront/issues/829

chore(header): limit max height and use scroll vertical

---

@ecomplus/storefront-components/src/js/BuyTogether.js

**Summary**
**Checklist**
**A picture of a cute animal**: I cant ( My girlfriend is too alergic. She need bombinha.)
After

fix(buy-together): watch subtotal and change discount

---

@ecomplus/storefront-components/src/html/ProductCard.html
@ecomplus/storefront-components/src/html/TheProduct.html
@ecomplus/storefront-components/src/js/ProductCard.js
@ecomplus/storefront-components/src/js/TheProduct.js
@ecomplus/storefront-components/src/scss/TheProduct.scss
@ecomplus/storefront-template/content/widgets/product.json
@ecomplus/widget-product/cms.config.js
@ecomplus/widget-product/src/index.js

**Summary**
Product card
Product
**Checklist**

feat(product): add upon request and quote product

---

@ecomplus/widget-fb-pixel/src/append/body.ejs

fix(fb-pixel): problem with load noscript pageview

---

@ecomplus/storefront-app/src/components/html/EcOrderInfo.html
@ecomplus/storefront-app/src/components/js/EcOrderInfo.js

feat(order-info): insert nfe on order

---

@ecomplus/storefront-components/src/html/AccountPoints.html
@ecomplus/storefront-components/src/html/TheAccount.html
@ecomplus/storefront-components/src/js/AccountPoints.js
@ecomplus/storefront-components/src/js/TheAccount.js
@ecomplus/storefront-components/src/scss/AccountPoints.scss
@ecomplus/storefront-components/src/scss/TheAccount.scss

feat(components/account-points): additional cashback info, render as account page tab

---

@ecomplus/storefront-renderer/functions/index.js
@ecomplus/storefront-template/content/widgets/fb-pixel.json
@ecomplus/storefront-template/template/pages/@/meta.ejs
@ecomplus/widget-fb-pixel/cms.config.js
@ecomplus/widget-fb-pixel/src/append/head.ejs

**Summary**
**Checklist**
Hora da verdade se saiu algo certo.

feat(proxy-reverse-fb): insert proxy reverse for partytown

---

@ecomplus/storefront-components/src/html/BuyTogether.html
@ecomplus/storefront-components/src/js/BuyTogether.js

chore(buy-together): insert related products into buy together

---

@ecomplus/storefront-components/src/js/TheAccount.js
@ecomplus/storefront-components/src/scss/TheAccount.scss

fix(the-account): remove vertical scroll and change method of insertion subscription tab

---

@ecomplus/storefront-template/template/scss/components/_header.scss

**Summary**
Without margin:
With margin:
**Checklist**

chore(scss): margin to overlaid button cancel search

---

@ecomplus/storefront-template/template/js/netlify-cms/base-config/collections/settings/stamps.js
@ecomplus/storefront-template/template/pages/@/sections/inc/product-item.ejs
@ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
@ecomplus/storefront-template/template/scss/components/_product-card.scss
@ecomplus/storefront-template/template/scss/components/_product.scss

chore(stamps): better ux for client selection

---

@ecomplus/storefront-renderer/functions/index.js

fix(renderer): Fix url error for reverse proxy usage

---

@ecomplus/storefront-components/src/html/TheProduct.html
@ecomplus/storefront-components/src/js/TheProduct.js

fixes https://github.com/ecomplus/storefront/issues/906
**Checklist**

chore(the-product): on change variation calculate shipping with his config

---

@ecomplus/widget-compre-confie/cms.config.js
@ecomplus/widget-compre-confie/src/append/stamps.ejs
@ecomplus/widget-compre-confie/src/index.js

chore(compre-confie): update to new script from acquired company

---

@ecomplus/storefront-components/src/html/ProductGallery.html

chore(product-gallery): loading lazy on youtube video inside product page

---

@ecomplus/widget-ebit/src/index.js

**Checklist**
Same issue compre confie

fix(ebit): set birth date only if has all props

---

@ecomplus/storefront-template/template/scss/components/_product.scss

chore(_product.scss): set width to 100% to avoid responsiveness problems in ios
